import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';

const dist = process.argv[2] || 'dist';

async function filesIn(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? filesIn(path) : [path];
  }));
  return files.flat();
}

const manifestPath = join(dist, 'manifest.webmanifest');
const manifest = await readFile(manifestPath, 'utf8');
const beforeVersion = await filesIn(dist);
const releaseInput = await Promise.all(beforeVersion
  .filter((file) => !file.endsWith('/sw.js') && !file.endsWith('\\sw.js') && !file.endsWith('.map'))
  .sort()
  .map(async (file) => `${relative(dist, file)}:${createHash('sha256').update(await readFile(file)).digest('hex')}`));
const version = createHash('sha256').update(releaseInput.join('\n')).digest('hex').slice(0, 16);

if (manifest.includes('__BUILD_VERSION__')) {
  await writeFile(manifestPath, manifest.replaceAll('__BUILD_VERSION__', version));
}

const allFiles = await filesIn(dist);
const precache = allFiles
  .filter((file) => !file.endsWith('/sw.js') && !file.endsWith('\\sw.js') && !file.endsWith('.map') && !file.endsWith('staticwebapp.config.json'))
  .map((file) => `/${relative(dist, file).replaceAll('\\', '/')}`)
  .sort();

const worker = `/* Generated by scripts/generate-sw.mjs. Release ${version}. */
const CACHE = 'milkdrop-web-${version}';
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(Promise.all([
    caches.keys().then((keys) => Promise.all(keys
      .filter((key) => key.startsWith('milkdrop-web-') && key !== CACHE)
      .map((key) => caches.delete(key)))),
    self.clients.claim(),
  ]));
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => caches.match('/index.html')));
    return;
  }
  event.respondWith(caches.match(request).then((cached) => cached || fetch(request)));
});
`;

await writeFile(join(dist, 'sw.js'), worker);
console.log(`Generated dist/sw.js for release ${version} with ${precache.length} precached files.`);
